-- RentalOps baseline schema.
-- Column types mirror what Hibernate 6 generates so `ddl-auto: validate` passes:
--   Instant      -> timestamp(6) with time zone
--   LocalDate    -> date
--   BigDecimal   -> numeric(38,2)
--   String/enum  -> varchar(255)

create table users (
    id            bigint generated by default as identity primary key,
    created_at    timestamp(6) with time zone not null,
    updated_at    timestamp(6) with time zone not null,
    full_name     varchar(255) not null,
    email         varchar(255) not null,
    password_hash varchar(255) not null,
    phone         varchar(255),
    status        varchar(255) not null,
    constraint uk_users_email unique (email),
    constraint ck_users_status check (status in ('ACTIVE', 'DISABLED'))
);

create table roles (
    id         bigint generated by default as identity primary key,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    name       varchar(255) not null,
    constraint uk_roles_name unique (name),
    constraint ck_roles_name check (name in ('ADMIN', 'PROPERTY_MANAGER', 'TENANT'))
);

create table user_roles (
    user_id bigint not null references users (id),
    role_id bigint not null references roles (id),
    primary key (user_id, role_id)
);

create table properties (
    id             bigint generated by default as identity primary key,
    created_at     timestamp(6) with time zone not null,
    updated_at     timestamp(6) with time zone not null,
    manager_id     bigint not null references users (id),
    name           varchar(255) not null,
    description    varchar(1500),
    address_line1  varchar(255) not null,
    address_line2  varchar(255),
    city           varchar(255) not null,
    state          varchar(255) not null,
    postal_code    varchar(255) not null,
    country        varchar(255) not null,
    property_type  varchar(255) not null,
    total_units    integer not null,
    occupied_units integer not null,
    status         varchar(255) not null,
    constraint ck_properties_type check (property_type in ('APARTMENT', 'HOUSE', 'COMMERCIAL', 'VILLA', 'STUDIO')),
    constraint ck_properties_status check (status in ('ACTIVE', 'INACTIVE'))
);
create index ix_properties_manager on properties (manager_id);

create table tenants (
    id                      bigint generated by default as identity primary key,
    created_at              timestamp(6) with time zone not null,
    updated_at              timestamp(6) with time zone not null,
    manager_id              bigint not null references users (id),
    user_id                 bigint references users (id),
    full_name               varchar(255) not null,
    email                   varchar(255) not null,
    phone                   varchar(255) not null,
    emergency_contact_name  varchar(255),
    emergency_contact_phone varchar(255),
    government_id_number     varchar(255),
    status                  varchar(255) not null,
    constraint ck_tenants_status check (status in ('ACTIVE', 'INACTIVE', 'PENDING'))
);
create index ix_tenants_manager on tenants (manager_id);
create index ix_tenants_user on tenants (user_id);

create table leases (
    id                 bigint generated by default as identity primary key,
    created_at         timestamp(6) with time zone not null,
    updated_at         timestamp(6) with time zone not null,
    property_id        bigint not null references properties (id),
    tenant_id          bigint not null references tenants (id),
    unit_number        varchar(255) not null,
    start_date         date not null,
    end_date           date not null,
    monthly_rent       numeric(38, 2) not null,
    security_deposit   numeric(38, 2) not null,
    lease_status       varchar(255) not null,
    agreement_file_url varchar(255),
    constraint ck_leases_status check (lease_status in ('DRAFT', 'ACTIVE', 'EXPIRED', 'TERMINATED'))
);
create index ix_leases_property on leases (property_id);
create index ix_leases_tenant on leases (tenant_id);

create table rent_payments (
    id                    bigint generated by default as identity primary key,
    created_at            timestamp(6) with time zone not null,
    updated_at            timestamp(6) with time zone not null,
    lease_id              bigint not null references leases (id),
    tenant_id             bigint not null references tenants (id),
    property_id           bigint not null references properties (id),
    amount_due            numeric(38, 2) not null,
    amount_paid           numeric(38, 2) not null,
    due_date              date not null,
    paid_date             date,
    payment_status        varchar(255) not null,
    payment_method        varchar(255),
    transaction_reference varchar(255),
    notes                 varchar(255),
    constraint ck_rent_payments_status check (payment_status in ('PENDING', 'PAID', 'OVERDUE', 'FAILED', 'PARTIAL')),
    constraint ck_rent_payments_method check (payment_method in ('CASH', 'BANK_TRANSFER', 'CARD', 'UPI', 'OTHER'))
);
create index ix_rent_payments_lease on rent_payments (lease_id);
create index ix_rent_payments_tenant on rent_payments (tenant_id);
create index ix_rent_payments_property on rent_payments (property_id);

create table maintenance_requests (
    id            bigint generated by default as identity primary key,
    created_at    timestamp(6) with time zone not null,
    updated_at    timestamp(6) with time zone not null,
    tenant_id     bigint not null references tenants (id),
    property_id   bigint not null references properties (id),
    title         varchar(255) not null,
    description   varchar(2000) not null,
    priority      varchar(255) not null,
    status        varchar(255) not null,
    manager_notes varchar(255),
    resolved_at   timestamp(6) with time zone,
    constraint ck_maintenance_priority check (priority in ('LOW', 'MEDIUM', 'HIGH', 'URGENT')),
    constraint ck_maintenance_status check (status in ('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED'))
);
create index ix_maintenance_tenant on maintenance_requests (tenant_id);
create index ix_maintenance_property on maintenance_requests (property_id);
