create table notifications (
    id           bigint generated by default as identity primary key,
    created_at   timestamp(6) with time zone not null,
    updated_at   timestamp(6) with time zone not null,
    recipient_id bigint not null references users (id),
    type         varchar(255) not null,
    title        varchar(255) not null,
    message      varchar(1000) not null,
    link_type    varchar(255),
    link_id      bigint,
    read_flag    boolean not null default false
);
create index ix_notifications_recipient on notifications (recipient_id, read_flag);
