-- Phase: production correctness + concurrency safety.
-- Moves in-memory state (password-reset tokens, login-attempt tracking) into the database,
-- adds a DB-based lock so scheduled jobs run once across a multi-instance deployment,
-- and adds optimistic-locking / integrity constraints to the core tables.

-- --- Password reset tokens (was an in-memory Map in AuthService) ------------------------
create table password_reset_tokens (
    id         bigint generated by default as identity primary key,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    user_id    bigint not null references users (id),
    token      varchar(255) not null,
    expires_at timestamp(6) with time zone not null,
    used       boolean not null default false,
    constraint uk_password_reset_tokens_token unique (token)
);
create index ix_password_reset_tokens_user on password_reset_tokens (user_id);

-- --- Login attempts (was an in-memory Map in LoginAttemptService) -----------------------
create table login_attempts (
    id            bigint generated by default as identity primary key,
    created_at    timestamp(6) with time zone not null,
    updated_at    timestamp(6) with time zone not null,
    email         varchar(255) not null,
    attempt_count integer not null,
    window_start  timestamp(6) with time zone not null,
    blocked_until timestamp(6) with time zone,
    constraint uk_login_attempts_email unique (email)
);

-- --- Job locks: cooperative single-runner lock for @Scheduled jobs ----------------------
create table job_locks (
    job_name     varchar(255) not null primary key,
    locked_until timestamp(6) with time zone not null,
    locked_by    varchar(255),
    updated_at   timestamp(6) with time zone not null
);

-- --- Rent billing idempotency: at most one charge per lease per due date ----------------
-- The billing loop already checks existsByLeaseIdAndDueDate; this makes it a hard guarantee
-- even under concurrent runs.
alter table rent_payments
    add constraint uk_rent_payments_lease_due unique (lease_id, due_date);

-- --- Optimistic locking on the entities most exposed to concurrent edits ---------------
alter table properties add column version bigint not null default 0;
alter table leases     add column version bigint not null default 0;

-- --- Property occupancy can never exceed capacity -------------------------------------
alter table properties
    add constraint ck_properties_occupancy check (occupied_units <= total_units);

-- --- At most one ACTIVE lease per unit (Postgres partial index) ------------------------
create unique index uk_leases_active_unit
    on leases (property_id, unit_number)
    where lease_status = 'ACTIVE';
