package com.rentalops.notification;

public enum NotificationType {
    RENT_DUE,
    RENT_OVERDUE,
    RENT_PAID,
    RENT_PAYMENT_REPORTED,
    RENT_PAYMENT_CONFIRMED,
    RENT_PAYMENT_UNCONFIRMED,
    LEASE_ACTIVATED,
    LEASE_EXPIRING,
    LEASE_EXPIRED,
    MAINTENANCE_CREATED,
    MAINTENANCE_UPDATED,
    ACCOUNT,
    GENERAL
}
